### ISSUE TITLE
轉換後失去章節

### ISSUE THREAD

**Issue by s4028600** [ThanatosDi/EpubConv_Python#11]
![1](https://user-images.githubusercontent.com/19856067/71766975-32ce9300-2f41-11ea-8eb2-17e7c8cf2385.png)
這是轉換成繁體前
![2](https://user-images.githubusercontent.com/19856067/71766990-5396e880-2f41-11ea-93b3-7b801d278a11.png)
這是轉換後
直接失去許多章節

**Comment by ThanatosDi** [comment]
你方便傳電子書到我的信箱嘛?
包含轉換時的 Log 紀錄檔
我的信箱: epubconv@mail.kawai.moe

**Comment by s4028600** [comment]
已寄出

**Comment by ThanatosDi** [comment]
![image](https://user-images.githubusercontent.com/12424898/71783248-fa04eb80-301e-11ea-8f7c-fa351c01ceed.png)
從你所附的兩個檔案並沒有任何章節缺少 請在確認一次並提供正確的 log 紀錄檔
這樣才能找到問題點

**Comment by s4028600** [comment]
我知道原因了
用7-zip打開確實章節沒有減少
是toc.ncx裡面的內容簡轉繁
但是連結的xhtml檔的名稱卻沒有簡轉繁
導致sigil讀取錯誤

**Comment by s4028600** [comment]
from zhconv import convert
import zipfile

name="看来我的身体天下无敌呢.epub"
z = zipfile.ZipFile(name, "r")
zw=zipfile.ZipFile(convert(name,'zh-tw'), "w",compression = zipfile.ZIP_DEFLATED)
for filename in z.namelist( ):
  print (filename)
  try:
  	content = convert(z.read(filename).decode('utf-8'),'zh-tw')
  	filename=convert(filename,'zh-tw')
  	zw.writestr(filename,content)
  except:
  	content = z.read(filename)
  	zw.writestr(filename,content)
zw.close()

用這樣很簡陋...
話說為什麼能拖曳檔案直接轉換阿
找不到類似的代碼
