### ISSUE TITLE
Epubconv ver.1.0.3.1 被 Windows判斷成病毒

### ISSUE THREAD

**Issue by gb63728f4** [ThanatosDi/EpubConv_Python#2]
Windows版本:1803
Chrome版本: 67.0.3396.87

Chrome擋一次，Windows內建防毒則是直接移除
雖然是可以設成白名單...
這邊稍微告知下

**Comment by Kutinging** [comment]
之前有使用者也回報給我這個問題，如果對於程式有疑慮可以自行安裝Python並下載source code執行

**Comment by Kutinging** [comment]
目前更新到 1.0.4.3 版本
使用VirusTotal掃描的結果如下
[https://www.virustotal.com/#/file/3059d.....](https://www.virustotal.com/#/file/3059de3421db0ce6ea8b22e6505a6369996dda9fdf75859d46069ccce151715e/detection)
應該可以判斷是之前版本被誤判，或者對於防毒軟體來說新增刪除重新命名檔案操作也在它的可疑範圍內
如果還有問題可以再回報給我，謝謝
