### ISSUE TITLE
Error function: convert, *msg: local variable 'opf' referenced before assignment

### ISSUE THREAD

**Issue by tkh0395** [ThanatosDi/EpubConv_Python#21]
Error when SC --> TC
screenshot and epub file zip below
-------------------------------------------------------------------------------------------------------------------------------------------
![Screenshot 2021-04-14 020254](https://user-images.githubusercontent.com/5292687/114661875-bbe88400-9cc5-11eb-83ba-40669673343e.png)

![Screenshot 2021-04-14 020231](https://user-images.githubusercontent.com/5292687/114661882-bee37480-9cc5-11eb-9224-1ac70ed24d85.png)
----------------------------------------------------------------------------------------------------------------------------------------------
[独自一人的异世界攻略001~104.zip](https://github.com/ThanatosDi/EpubConv_Python/files/6308511/001.104.zip)

**Comment by ThanatosDi** [comment]
OK, I will find out the problem and fix it.

**Comment by tkh0395** [comment]
thanks
