### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by tkh0395** [ThanatosDi/EpubConv_Python#5]
轉不了求救, list index out of range

[关于我转生成为史莱姆的那件事 09卷.zip](https://github.com/ThanatosDi/EpubConv_Python/files/2699320/09.zip)

![screenshot 10](https://user-images.githubusercontent.com/5292687/50291907-ccfa9080-043d-11e9-9396-0ee0750da41c.png)

**Comment by tkh0395** [comment]
![screenshot 10](https://user-images.githubusercontent.com/5292687/50292138-5e6a0280-043e-11e9-82af-be20fcada21b.png)

**Comment by ThanatosDi** [comment]
好，我會花時間來處理這個問題

**Comment by ThanatosDi** [comment]
目前已經處理完成 在1.0.5.2版本已修正該問題
