### ISSUE TITLE
是否考慮加入以繁化姬 API 轉換的選項

### ISSUE THREAD

**Issue by rexx0520** [ThanatosDi/EpubConv_Python#6]
如題，畢竟繁化姬真的很好用
謝謝

**Comment by ThanatosDi** [comment]
這個部份我會加入考慮，現階段我想要先把整個程式的程式碼做整理，可能整個架構上會有大幅度的變化
而且我應該會拔除掉電子書內的檔案編碼判斷這個功能，主要還是希望使用者在檔案編碼上面都統一使用 'UTF-8' 格式，那預計要出的UI版本的話可能會暫時不會再進行開發

**Comment by rexx0520** [comment]
https://github.com/rexx0520/EPUB_Taiwanize
姑且寫了可以用的版本
看您有沒有興趣合併兩個版本（？）

**Comment by ThanatosDi** [comment]
在 v2.0.0版本中我已經加入了繁化姬的轉換選項
雖然在轉換上可能效率沒這麼好，這塊之後會看要用什麼方法解決
除了繁化姬、opencc之外當初我還考慮要用Google的翻譯，但我還沒實作完成
如果還有好的建議可以在跟我討論討論XD
畢竟這個程式也是我當初心血來潮寫的XD

**Comment by rexx0520** [comment]
我的版本裡面是有依照繁化姬的 max size 去做分塊上傳啦
比起一行一行上傳效率會好得多

然後我還有做一個網頁轉換跟 Dockerfile，尼也可以考慮加進去XD

**Comment by ThanatosDi** [comment]
大致上我是算過小說一個章節是不大會超出繁化姬的最大限制 2,000,000 ，但在這邊我已經可以預想到現在 v2.0.0 可能會發生的BUG了XD
之後我可能會用異部處理的方式去處理
