### ISSUE TITLE
能否增加參數設定?

### ISSUE THREAD

**Issue by bgtsai** [ThanatosDi/EpubConv_Python#7]
01. 取消--完成時的按任何鍵
      原因 : 使用命令列執行時，如轉換多檔案 (遍歷資料夾裡的每一檔案)，在完成第一個檔案時就會卡住
02. 可指定輸出資料夾
      原因 : 方便整理 (我個人有沒有轉檔的東西是不會放在一起，不曉得有多少人有這需求)

**Comment by ThanatosDi** [comment]
關於你的問題我大致上來說明一下

1. 這個部分可能還是不會取消，但是在執行轉換之前可以使用遍歷取得檔案 list 之後再用 join 的方式達到如下方的結果
```python
<file 1 path> <file 2 path> <file 3 path>
```
之後再執行轉換
```python
python app2.py <file 1 path> <file 2 path> <file 3 path>
```
2. 參數部分可能會等到整體的程式比較沒有BUG之後才會加入所以可能要稍待一段時間，主體還是 for windows 用戶為主

**Comment by bgtsai** [comment]
我之前的問題描述的不夠清楚
我個人是在 windows 平台使用，另外用 vbscript 去執行 epubconv
只因在執行 epubconv 的前後都另有動作
所以才想說是否能以在 config.json 中進行設定，完成預設提問中 1 與 2 功能

**Comment by ThanatosDi** [comment]
如果要像 cli 這部分的可能要等日後有空才會再另外弄，這個版本我主要還是給一般的使用者使用
個人是比較趨向於如果可以的話可以用 vbscript 呼叫外部函數 python 執行 .py ，當然要事先配置 python 環境
因為個人現在還是學生加上又要打工所以比較沒有時間可以再另外開發XD
